revert but fail if we aren't successful creating the repo

diff --git a/.github/workflows/create-google-package-sync.yaml b/.github/workflows/create-google-package-sync.yaml
--- a/.github/workflows/create-google-package-sync.yaml
+++ b/.github/workflows/create-google-package-sync.yaml
@@ -23,18 +23,24 @@ jobs:
 
             echo "Creating repository for $package"
             # Retry the operation up to 3 times
+            success=false
             for attempt in {1..3}
             do
-              output=$(gh repo create RageAgainstThePixel/$package --public --template RageAgainstThePixel/google-package-archive-template 2>&1) || echo "Error: $output"
+              output=$(gh repo create RageAgainstThePixel/$package --public --template RageAgainstThePixel/google-package-archive-template 2>&1)
               if [[ $output == *"HTTP 5"* ]]
               then
                 echo "Server error, waiting before retrying..."
                 sleep 10
               else
                 echo "Repository created successfully."
+                success=true
                 break
               fi
             done
+            if [ "$success" = false ] ; then
+              echo "Failed to create repository after 3 attempts."
+              exit 1
+            fi
 
             # Poll for the workflow file to be available
             for i in {1..10}
