echo output

diff --git a/.github/workflows/create-google-package-sync.yaml b/.github/workflows/create-google-package-sync.yaml
--- a/.github/workflows/create-google-package-sync.yaml
+++ b/.github/workflows/create-google-package-sync.yaml
@@ -25,7 +25,7 @@ jobs:
             # Retry the operation up to 3 times
             for attempt in {1..3}
             do
-              output=$(gh repo create RageAgainstThePixel/$package --public --template RageAgainstThePixel/google-package-archive-template 2>&1)
+              output=$(gh repo create RageAgainstThePixel/$package --public --template RageAgainstThePixel/google-package-archive-template 2>&1) || echo "Error: $output"
               if [[ $output == *"HTTP 5"* ]]
               then
                 echo "Server error, waiting before retrying..."
