dry run

diff --git a/.github/workflows/create-google-package-sync.yaml b/.github/workflows/create-google-package-sync.yaml
--- a/.github/workflows/create-google-package-sync.yaml
+++ b/.github/workflows/create-google-package-sync.yaml
@@ -14,7 +14,7 @@ jobs:
       - name: generate synced google package repository
         run: |
           set -e
-          packages=$(curl -sS https://developers.google.com/unity/archive | grep -oP 'com.google[^<]*-\K\d+\.\d+\.\d+(?=\.tgz)' | cut -d'/' -f1 | sort -u)
+          packages=$(curl -sS https://developers.google.com/unity/archive | grep -oP 'com.google[^<]*\.tgz' | cut -d'/' -f1 | sort -u)
           echo $packages
           for package in $packages; do
             if gh repo view RageAgainstThePixel/$package >/dev/null 2>&1; then
@@ -23,40 +23,40 @@ jobs:
 
             echo "Creating repository for $package"
             # Retry the operation up to 3 times
-            success=false
-            for attempt in {1..3}
-            do
-              output=$(gh repo create RageAgainstThePixel/$package --public --template RageAgainstThePixel/google-package-archive-template 2>&1)
-              if [[ $output == *"HTTP 5"* ]]
-              then
-                echo $output
-                echo "Server error, waiting before retrying..."
-                sleep 10
-              else
-                echo "\033[0;32mRepository created successfully @ https://github.com/RageAgainstThePixel/$package \033[0m"
-                success=true
-                break
-              fi
-            done
-            if [ "$success" = false ] ; then
-              echo "::error:: Failed to create repository after 3 attempts."
-              exit 1
-            fi
+            # success=false
+            # for attempt in {1..3}
+            # do
+            #   output=$(gh repo create RageAgainstThePixel/$package --public --template RageAgainstThePixel/google-package-archive-template 2>&1)
+            #   if [[ $output == *"HTTP 5"* ]]
+            #   then
+            #     echo $output
+            #     echo "Server error, waiting before retrying..."
+            #     sleep 10
+            #   else
+            #     echo "Repository created successfully @ https://github.com/RageAgainstThePixel/$package"
+            #     success=true
+            #     break
+            #   fi
+            # done
+            # if [ "$success" = false ] ; then
+            #   echo "::error:: Failed to create repository after 3 attempts."
+            #   exit 1
+            # fi
 
-            # Poll for the workflow file to be available
-            for i in {1..10}
-            do
-              echo "Checking if workflow file is available ($i/10)..."
-              if gh workflow view upm-sync.yaml -R RageAgainstThePixel/$package > /dev/null 2>&1
-              then
-                  echo "Workflow file is available, running workflow..."
-                  gh workflow run upm-sync.yaml -R RageAgainstThePixel/$package
-                  break
-              else
-                  echo "Workflow file is not available yet, waiting..."
-                  sleep 10
-              fi
-            done
+            # # Poll for the workflow file to be available
+            # for i in {1..10}
+            # do
+            #   echo "Checking if workflow file is available ($i/10)..."
+            #   if gh workflow view upm-sync.yaml -R RageAgainstThePixel/$package > /dev/null 2>&1
+            #   then
+            #       echo "Workflow file is available, running workflow..."
+            #       gh workflow run upm-sync.yaml -R RageAgainstThePixel/$package
+            #       break
+            #   else
+            #       echo "Workflow file is not available yet, waiting..."
+            #       sleep 10
+            #   fi
+            # done
           done
         env:
           GH_TOKEN: ${{ secrets.CI_TOKEN }}
